export { RiPhoneFill } from "react-icons/ri"
export { MdEmail } from "react-icons/md"
export { BsHandbagFill } from "react-icons/bs"
export { FaUserCircle } from "react-icons/fa"
export { AiFillHome, AiFillStar, AiOutlineStar } from "react-icons/ai"
