export const path = {
	HOME: "/",
	LOGIN: "/login",
	REGISTER: "/register",
	FORGOT_PASSWORD: "/forgot-password",
	PRODUCTS: "/products",
	BLOGS: "/blog",
	OUR_SERVICES: "/our-services",
	ABOUT_US: "/about-us",
	CONTACT_US: "/contact-us",
	FAQS: "/faqs",
	CART: "/cart",

	ADMIN: "/admin",
	DASHBOARD: "dashboard",
	MANAGE_USER: "manage-user",
	MANAGE_PRODUCTS: "manage-products",
	MANAGE_ORDERS: "manage-orders",
	CREATE_PRODUCTS: "create-products",
	MANAGE_BRANDS: "manage-brands",
	CREATE_BRAND: "create-brand",
	MANAGE_CATEGORIES: "manage-categories",
	CREATE_CATEGORY: "create-category",
	MANAGE_BLOGS: "manage-blogs",
	CREATE_BLOG: "create-blog",
	MANAGE_BLOG_CATEGORIES: "manage-blog-categories",
	MANAGE_CHAT_ROOMS: "manage-chat",

	MEMEBER: "/member",

	PROFILE: "/profile",
	ORDERS: "orders",
	WISHLIST: "wishlist",
}
