import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import { AdminSidebar, Toast } from "@/components"
import clsx from "clsx"
import { anton, bebasNeue, inter, poppins } from "@/utils"
import "../globals.css"
import { AuthProvider, ReduxProvider } from "@/context"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

const bodyClassName = clsx(
	"w-full flex flex-col items-center min-h-screen",
	poppins.variable,
	anton.variable,
	inter.variable,
	bebasNeue.variable
)

export default function AdminLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={bodyClassName}>
				<ReduxProvider>
					<AuthProvider>
						<Toast />
						<div className="flex flex-grow w-full">
							<AdminSidebar />
							{children}
						</div>
					</AuthProvider>
				</ReduxProvider>
			</body>
		</html>
	)
}
