import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import { AdminSidebar, ScrollToTop, Toast } from "@/components"
import clsx from "clsx"
import { anton, bebasNeue, inter, poppins } from "@/utils"
import "../globals.css"
import { AuthProvider, ReduxProvider } from "@/context"
import { GoogleOAuthProvider } from "@react-oauth/google"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

const bodyClassName = clsx(
	"w-full flex flex-col items-center min-h-screen",
	poppins.variable,
	anton.variable,
	inter.variable,
	bebasNeue.variable
)

export default function AdminLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={bodyClassName}>
				<GoogleOAuthProvider
					clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}
				>
					<ReduxProvider>
						<AuthProvider>
							<Toast />
							<div className="w-full xl:w-main flex-grow flex flex-col">
								<AdminSidebar />
								{children}
							</div>
							<div className="fixed bottom-2 right-0 max-sm:w-full md:bottom-4 md:right-4 flex flex-col-reverse gap-2 items-end z-10">
								<ScrollToTop />
							</div>
						</AuthProvider>
					</ReduxProvider>
				</GoogleOAuthProvider>
			</body>
		</html>
	)
}
